name: 'Docker Publish'

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/docker-description.yml
jobs:
  sync:
    name: Docker README.md Sync
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: DockerHub Description
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: 'polandj/vaultwarden-rclone'
